CREATE TABLE TEST(
     ID NUMBER(4),
     NAME VARCHAR2(3));
DESC TEST;


INSERT INTO TEST VALUES(1000, 'È«±æµ¿');
INSERT INTO TEST VALUES(1000, 'ABC');

CREATE TABLE TEST2(
     ID NCHAR(4),
     NAME NVARCHAR2(3));
     
INSERT INTO TEST2 VALUES('È²º¸°­¼º', 'È«±æµ¿');


